#!/bin/bash -e

IMAGE_NAME=$3
BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"

FULL_IMAGE_NAME=${IMAGE_NAME}:${BITBUCKET_COMMIT_SHORT}

docker login -u $DOCKER_USER -p "$DOCKER_PASS" $CONTAINER_REPOSITORY
docker build --force-rm -t "$FULL_IMAGE_NAME" -f $1 $2 --build-arg PIP_PACKAGES=pip-packages
docker tag "$FULL_IMAGE_NAME" $IMAGE_NAME:$BITBUCKET_BRANCH
docker tag "$FULL_IMAGE_NAME" $IMAGE_NAME:$BITBUCKET_BRANCH-$BITBUCKET_BUILD_NUMBER-$BITBUCKET_COMMIT_SHORT

docker push "$FULL_IMAGE_NAME"
